### ISSUE TITLE
Feature Request - Email notifications

### ISSUE THREAD

**Issue by rmoore3** [ExtremeNetworksSA/XIQ-AD-User-Sync#2]
Feature Request - Email notifications

Option for success or failure email notifications.

**Comment by timjsmith24** [comment]
I can look into this. 
Do you manage your ouwn SMTP server? Or do you use Office365 or Google?

In my home lab, I have the script send a slack notification if there are failures. Would that be something that would work?

**Comment by rmoore3** [comment]
While we are a Google shop, we use an internal smtp replay server for most of our notifications. Notifications just for failures would be great.

**Comment by timjsmith24** [comment]
Ok, I created a snakedogipa branch. This has both the email for errors and the AD user stuff from the other request. See if that works for you. 
There's a section at the top - lines 56-61 where you will need to add your SMTP settings

**Comment by rmoore3** [comment]
Much appreciated

**Comment by rmoore3** [comment]
It sends an email every time but does not contain any information. Can it
be set to only send on an error and include the error in the body of the
email?


Ron Moore

Senior HelpDesk Technician

Brenau University

Office Hours: M-F 8:30AM-5:00PM


Consider the environment: Stop Printing, Start Sharing - Google Drive
<https://drive.google.com/>

------------------------------

CONFIDENTIALITY NOTICE: This email and any attachments are confidential and
may also be privileged. If you are not the named recipient, please notify
the sender immediately and delete the contents of this message without
disclosing the contents to anyone, using them for any purpose, or storing
or copying the information on any medium.

**Comment by rmoore3** [comment]
Disregard. Looks like I made a typo.


Ron Moore

Senior HelpDesk Technician

Brenau University

Office Hours: M-F 8:30AM-5:00PM


Consider the environment: Stop Printing, Start Sharing - Google Drive
<https://drive.google.com/>

------------------------------

CONFIDENTIALITY NOTICE: This email and any attachments are confidential and
may also be privileged. If you are not the named recipient, please notify
the sender immediately and delete the contents of this message without
disclosing the contents to anyone, using them for any purpose, or storing
or copying the information on any medium.
