### ISSUE TITLE
feature request:  remove special characters from names / usernames pulled from active directory

### ISSUE THREAD

**Issue by WombatSandwich** [ExtremeNetworksSA/XIQ-AD-User-Sync#3]
we have a number of users in AD with an apostrophe in their name.

now cloud based groups in xiq have no problem with the apostrophe in the name, but local groups error out when you sync a user with an apostrophe in their name.

would you be able to remove any special characters from the names returned from AD?

**Comment by timjsmith24** [comment]
We actually have an open GTAC case for this. Let me check the status of that. If it's something that can't or won't be fixed in the backend, I will take a look at this.

**Comment by timjsmith24** [comment]
Apostrophes are now accepted for users in XIQ, so there is no need to remove them from the AD users.
