### ISSUE TITLE
Unable to reach server

### ISSUE THREAD

**Issue by kevrodg** [ExtremeNetworksSA/XIQ-AD-User-Sync#4]
I'm getting an Unable to reach server error. I confirmed it's not a network issue. Here's my environment:

Ubuntu 22.04.2
Python 3.10.12
pip 22.0.2
ldap3 2.9.1
requests 2.25.1

**Comment by timjsmith24** [comment]
Can you run the AD_Test.py script and send the response? This script will give more details on why the script cannot access data from the ldap server.

**Comment by kevrodg** [comment]
I'm getting this error when running AD_Test.py:

`Traceback (most recent call last):
  File "/home/linuxadmin/.local/lib/python3.10/site-packages/ldap3/utils/ntlm.py", line 500, in ntowf_v2
    from Crypto.Hash import MD4  # try with the Crypto library if present
ModuleNotFoundError: No module named 'Crypto'`

**Comment by kevrodg** [comment]
I installed pycryptodome and it's all working now.

**Comment by timjsmith24** [comment]
Yep, looks like an issue with the LDAP module
https://github.com/cannatag/ldap3/issues/1051

I will test to see if it's related to Ubuntu or Python 3.10. I may end up adding pycryptodome to the requirements.txt file. 

Glad you got it working!

**Comment by rmoore3** [comment]
I updated from  3.11.2 to 3.11.5 on Windows and have the same issue. Adding pycryptodome fixes the AD_Test.py script, but did not fix the XIQ-AD-User-Sync.py. I receive an error "Unable to reach server server.name.here".

**Comment by timjsmith24** [comment]
I assume you changed the output to"server.name.here" and that is not what you have to the server_name variable.
Can we set up a call to take a look? My email is tismith@extremenetworks.com
